# This line causes rustfmt 0.6.2 to panic:
reorder_imports = true
reorder_imported_names = true
use_try_shorthand = true
wrap_comments = true
normalize_comments = true
condense_wildcard_suffices = true
#write_mode = WriteMode::Overwrite

